# Site settings
title: The Altered Path
header-img: img/home-bg.png
email: mike.katz@outlook.com
copyright_name: mikek4
description: > # this means to ignore newlines until "baseurl:"
  Changing My Career
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: michaelrkatz
github_username:  mikek4
learn_profile: mikek4
email_username: mike.katz@outlook.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
